#Hello there person editing this config, here you can change
#the economical value outputs for every individual setting.

#This is when a player kills another player:

pvp:
  onKill: 20
  onDeath: 20
  enabled: true

#Died by a mob? Change on death values here:

pve:
  onDeath: 50
  enabled: false

#Environmental deaths are a thing too:

env:
  onDeath: 20
  enabled: false